##########################################
# Author: Kepler Ridge
# Date: 7/29/24
# Prompt: Each new term in the Fibonacci sequencee is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
##########################################

#%%
def build_fib_list(fibonacci_list):
    if fibonacci_list[-1] < 4000000:
        fibonacci_list.append((fibonacci_list[-1] + fibonacci_list[-2]))
        build_fib_list(fibonacci_list)

    return fibonacci_list
    
fib_list = build_fib_list([1, 2])

fib_even_sum = 0

for num in fib_list:
    if num % 2 == 0:
        fib_even_sum += num

#%%
print(fib_even_sum)

# Answer: 4613732